color: null
fieldLayouts:
  a7b80432-1635-4392-b20c-c644a4a9ba60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-17T22:12:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ce26faa-8bd8-43ec-af90-f133b38bd0bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-17T22:12:27+00:00'
            elementCondition: null
            fieldUid: 2756b662-d94c-4ff3-8181-1381adeda04e # Heading Select
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da24896d-0987-4b43-be99-9c95d28b04d9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c72bd60-f2c2-46fd-87b5-51882d73aef7
        userCondition: null
handle: Heading
hasTitleField: true
icon: heading
name: Heading
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
