color: null
fieldLayouts:
  566b40f7-fdca-4de0-9204-e846f63aa6dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-07T16:59:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1a3025ab-f9d1-4ce2-b312-ad51803cb949
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T17:18:49+00:00'
            elementCondition: null
            fieldUid: 9eb362d7-38b1-4629-94d8-b4fc5afe4732 # Image
            handle: featureImage
            includeInCards: false
            instructions: null
            label: 'Feature Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdc87028-09e7-44cc-abc3-3d4d34db68a1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T17:18:49+00:00'
            elementCondition: null
            fieldUid: d41991e3-1d36-435e-8954-7cb343967f11 # Text
            handle: summary
            includeInCards: false
            instructions: null
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4b82993-917d-49f8-a863-763576d0872b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T17:18:49+00:00'
            elementCondition: null
            fieldUid: 99380ab5-8e60-40c1-8607-a42c87cde8d9 # Post Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05772f49-256d-4656-aea4-48df7783ed61
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-07T17:18:49+00:00'
            elementCondition: null
            fieldUid: 3470150a-8a81-44d3-bb85-60b7b3706ffd # Post Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00eadf80-abe2-4225-be58-57894e0d0654
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43464bc5-0a18-41ed-9a7f-5ab619786bfd
        userCondition: null
handle: post
hasTitleField: true
icon: pen
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
