color: null
fieldLayouts:
  94e0bcd2-646f-4922-a957-abfe73c9940f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-15T23:02:18+00:00'
            elementCondition: null
            fieldUid: d41991e3-1d36-435e-8954-7cb343967f11 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd5f7b42-ec65-4fe3-a707-eb6669e619aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 07fb0691-928b-4c74-b7f5-c1ce1f395ab2
        userCondition: null
handle: quote
hasTitleField: false
icon: quotes
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
