color: null
fieldLayouts:
  a7b80432-1635-4392-b20c-c644a4a9ba60:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-21T16:40:08+00:00'
            elementCondition: null
            fieldUid: d41991e3-1d36-435e-8954-7cb343967f11 # Text
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 994af85a-cc41-4ae2-b172-b2e148362c0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-21T16:40:08+00:00'
            elementCondition: null
            fieldUid: ff9d2595-7e12-499c-ab83-9eb1af4a6414 # Short text (64 char)
            handle: cite
            includeInCards: false
            instructions: null
            label: 'cited person'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18f4d8e8-f682-4f7c-a8e2-2d51238622e8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0c72bd60-f2c2-46fd-87b5-51882d73aef7
        userCondition: null
handle: quote
hasTitleField: false
icon: quotes
name: Quote
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
