color: null
fieldLayouts:
  77e48136-5667-45f8-92b7-26990bf42a26:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-26T23:08:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 506220a0-a2a7-4ba9-a001-608709930493
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-26T23:11:47+00:00'
            elementCondition: null
            fieldUid: d41991e3-1d36-435e-8954-7cb343967f11 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 853937fe-817e-4503-965e-6edfb4ed3f8a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-26T23:11:47+00:00'
            elementCondition: null
            fieldUid: bf7362e6-3c1a-4896-a50f-df8a628fb09f # Multiple images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4bb90f0-ee4b-419f-99f1-61c47d5ec141
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f1ad1db5-3d11-4a98-a714-326202fe25b5
        userCondition: null
handle: sliderComponent
hasTitleField: true
icon: images
name: 'Slider Component'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
