color: null
fieldLayouts:
  808d9bb4-ed34-4fad-8bf0-8f0b53e27fb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-21T16:12:37+00:00'
            elementCondition: null
            fieldUid: e85b9150-15ea-4f7f-bb34-676ca47a09b4 # WYSIWYG
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4523bbb3-87ae-4066-82c4-bec6fccc48f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 11f7a951-4150-4f06-a0fe-6a4d8ddf59e2
        userCondition: null
handle: text
hasTitleField: false
icon: text
name: Text
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
