columnSuffix: null
handle: adress
instructions: null
name: Adress
searchable: true
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
