columnSuffix: null
handle: headers
instructions: null
name: Headers
searchable: false
settings:
  createButtonLabel: 'New header'
  defaultIndexViewMode: cards
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d966c555-3b5e-4954-8210-b70f5eedb9e4 # Primary header
  includeTableView: false
  maxEntries: 1
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
