dateModified: 1734464855
email:
  fromEmail: sanderjverhoeven@gmail.com
  fromName: 'Component system'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@uploads'
meta:
  __names__:
    3bac29b9-0eea-404e-b5dc-6f278cee619a: Text # Text
    3d6a182b-ed5a-4f35-acaf-b3198a90b978: Homepage # Homepage
    04d3913c-b661-4350-b02e-d58a7684a0cd: siteInfo # siteInfo
    7ba054cd-05ba-42a7-8af3-c9e518519b9f: 'Component system' # Component system
    82c6d396-89e5-4844-8742-535861bfab2f: Home # Home
    8348fd5e-83b6-4372-9f85-b1cb8ce6d097: Topics # Topics
    6592931d-6f2e-40dc-80c8-f296eb428e5f: Images # Images
    d41991e3-1d36-435e-8954-7cb343967f11: Text # Text
    ebcb3ddb-d136-47be-974b-87155e593ce2: 'Component system' # Component system
system:
  edition: solo
  live: true
  name: 'Component system'
  schemaVersion: 5.5.0.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
