fieldLayouts:
  f01fb797-0e58-44a9-b181-4727f0fe62d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-06T21:59:53+00:00'
            elementCondition: null
            fieldUid: 50c0c964-8043-401d-9559-d368791c5b01 # Navigation Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f40e624-a8d6-44a8-8556-c91fb28c7dda
            userCondition: null
            warning: null
            width: 100
        name: 'Navigation items'
        uid: 8d353bab-c7c0-4e75-a355-5c5bab1aca32
        userCondition: null
handle: navigation
name: Navigation
sortOrder: 2
