fieldLayouts:
  59e9d47e-fb14-46ef-bb8b-138a5182824b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-01-17T22:38:19+00:00'
            elementCondition: null
            fieldUid: 52b3db2e-4152-4686-a155-7d3c88321540 # Single image
            handle: cardImage
            includeInCards: false
            instructions: null
            label: 'Card image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8320161-5519-4359-b2d7-fe0cd6688212
            userCondition: null
            warning: null
            width: 100
        name: Placeholder
        uid: 7aff61e6-31d7-4a7b-b7d4-271504058191
        userCondition: null
handle: placeholders
name: Placeholders
sortOrder: 3
