defaultPlacement: end
enableVersioning: true
entryTypes:
  - 6640b7e7-a059-470e-975a-cca954ef2a71 # About
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ebcb3ddb-d136-47be-974b-87155e593ce2: # Component system
    enabledByDefault: true
    hasUrls: true
    template: singles/_entry.twig
    uriFormat: about
type: single
