defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 82c6d396-89e5-4844-8742-535861bfab2f # Section | Default
handle: pages
maxAuthors: 1
name: 'Pagina''s'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ebcb3ddb-d136-47be-974b-87155e593ce2: # Component system
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 48765443-5c2a-4f52-a169-ae73c8cddf58
type: structure
