defaultPlacement: end
enableVersioning: true
entryTypes:
  - d88fb071-a241-4a66-b038-2bdf25155e17 # Section | Projects
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ebcb3ddb-d136-47be-974b-87155e593ce2: # Component system
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'projecten/{slug}'
type: channel
