defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e4c65bcd-096c-4a93-969d-bf2338cb005f # Section | Services
handle: services
maxAuthors: 1
name: Services
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ebcb3ddb-d136-47be-974b-87155e593ce2: # Component system
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'services/{slug}'
type: channel
